import type { ThemePreset } from "../types/theme";

export const shadcnThemePresets: Record<string, ThemePreset> = {
  "default": {
    label: "Default",
    styles: {
      light: {
        background: "#0a0e1a",
        foreground: "#e2e8f0",
        card: "#0f1428",
        "card-foreground": "#e2e8f0",
        popover: "#0f1428",
        "popover-foreground": "#e2e8f0",
        primary: "#00c6ff",
        "primary-foreground": "#000000",
        secondary: "#151d35",
        "secondary-foreground": "#e2e8f0",
        muted: "#151d35",
        "muted-foreground": "#6b7a99",
        accent: "#151d35",
        "accent-foreground": "#e2e8f0",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "rgba(255, 255, 255, 0.08)",
        input: "rgba(255, 255, 255, 0.08)",
        ring: "#00c6ff",
        "chart-1": "#00c6ff",
        "chart-2": "#34d399",
        "chart-3": "#a78bfa",
        "chart-4": "#fbbf24",
        "chart-5": "#f87171",
        radius: "0.625rem",
        sidebar: "#080c16",
        "sidebar-foreground": "#e2e8f0",
        "sidebar-primary": "#00c6ff",
        "sidebar-primary-foreground": "#000000",
        "sidebar-accent": "#111827",
        "sidebar-accent-foreground": "#e2e8f0",
        "sidebar-border": "rgba(255, 255, 255, 0.06)",
        "sidebar-ring": "#00c6ff",
      },
      dark: {
        background: "#0a0e1a",
        foreground: "#e2e8f0",
        card: "#0f1428",
        "card-foreground": "#e2e8f0",
        popover: "#0f1428",
        "popover-foreground": "#e2e8f0",
        primary: "#00c6ff",
        "primary-foreground": "#000000",
        secondary: "#151d35",
        "secondary-foreground": "#e2e8f0",
        muted: "#151d35",
        "muted-foreground": "#6b7a99",
        accent: "#151d35",
        "accent-foreground": "#e2e8f0",
        destructive: "#ef4444",
        "destructive-foreground": "#ffffff",
        border: "rgba(255, 255, 255, 0.08)",
        input: "rgba(255, 255, 255, 0.08)",
        ring: "#00c6ff",
        "chart-1": "#00c6ff",
        "chart-2": "#34d399",
        "chart-3": "#a78bfa",
        "chart-4": "#fbbf24",
        "chart-5": "#f87171",
        radius: "0.625rem",
        sidebar: "#080c16",
        "sidebar-foreground": "#e2e8f0",
        "sidebar-primary": "#00c6ff",
        "sidebar-primary-foreground": "#000000",
        "sidebar-accent": "#111827",
        "sidebar-accent-foreground": "#e2e8f0",
        "sidebar-border": "rgba(255, 255, 255, 0.06)",
        "sidebar-ring": "#00c6ff",
      }
    }
  },
  "blue": {
    label: "Blue",
    styles: {
      light: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        card: "oklch(1 0 0)",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "oklch(1 0 0)",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "var(--color-blue-600)",
        "primary-foreground": "var(--color-blue-50)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "var(--color-blue-400)",
        "chart-1": "var(--color-blue-500)",
        "chart-2": "var(--color-blue-600)",
        "chart-3": "var(--color-blue-700)",
        "chart-4": "var(--color-blue-800)",
        "chart-5": "var(--color-blue-900)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      },
      dark: {
        background: "oklch(0.145 0 0)",
        foreground: "oklch(0.985 0 0)",
        card: "oklch(0.205 0 0)",
        "card-foreground": "oklch(0.985 0 0)",
        popover: "oklch(0.269 0 0)",
        "popover-foreground": "oklch(0.985 0 0)",
        primary: "var(--color-blue-500)",
        "primary-foreground": "var(--color-blue-50)",
        secondary: "oklch(0.269 0 0)",
        "secondary-foreground": "oklch(0.985 0 0)",
        muted: "oklch(0.269 0 0)",
        "muted-foreground": "oklch(0.708 0 0)",
        accent: "oklch(0.371 0 0)",
        "accent-foreground": "oklch(0.985 0 0)",
        destructive: "oklch(0.704 0.191 22.216)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(1 0 0 / 10%)",
        input: "oklch(1 0 0 / 15%)",
        ring: "var(--color-blue-900)",
        "chart-1": "var(--color-blue-400)",
        "chart-2": "var(--color-blue-500)",
        "chart-3": "var(--color-blue-600)",
        "chart-4": "var(--color-blue-700)",
        "chart-5": "var(--color-blue-800)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      }
    }
  },
  "green": {
    label: "Green",
    styles: {
      light: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        card: "oklch(1 0 0)",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "oklch(1 0 0)",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "var(--color-lime-600)",
        "primary-foreground": "var(--color-lime-50)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "var(--color-lime-400)",
        "chart-1": "var(--color-lime-500)",
        "chart-2": "var(--color-lime-600)",
        "chart-3": "var(--color-lime-700)",
        "chart-4": "var(--color-lime-800)",
        "chart-5": "var(--color-lime-900)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      },
      dark: {
        background: "oklch(0.145 0 0)",
        foreground: "oklch(0.985 0 0)",
        card: "oklch(0.205 0 0)",
        "card-foreground": "oklch(0.985 0 0)",
        popover: "oklch(0.269 0 0)",
        "popover-foreground": "oklch(0.985 0 0)",
        primary: "var(--color-lime-500)",
        "primary-foreground": "var(--color-lime-50)",
        secondary: "oklch(0.269 0 0)",
        "secondary-foreground": "oklch(0.985 0 0)",
        muted: "oklch(0.269 0 0)",
        "muted-foreground": "oklch(0.708 0 0)",
        accent: "oklch(0.371 0 0)",
        "accent-foreground": "oklch(0.985 0 0)",
        destructive: "oklch(0.704 0.191 22.216)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(1 0 0 / 10%)",
        input: "oklch(1 0 0 / 15%)",
        ring: "var(--color-lime-900)",
        "chart-1": "var(--color-lime-400)",
        "chart-2": "var(--color-lime-500)",
        "chart-3": "var(--color-lime-600)",
        "chart-4": "var(--color-lime-700)",
        "chart-5": "var(--color-lime-800)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      }
    }
  },
  "red": {
    label: "Red",
    styles: {
      light: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        card: "oklch(1 0 0)",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "oklch(1 0 0)",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "var(--color-red-600)",
        "primary-foreground": "var(--color-red-50)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "var(--color-red-400)",
        "chart-1": "var(--color-red-500)",
        "chart-2": "var(--color-red-600)",
        "chart-3": "var(--color-red-700)",
        "chart-4": "var(--color-red-800)",
        "chart-5": "var(--color-red-900)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      },
      dark: {
        background: "oklch(0.145 0 0)",
        foreground: "oklch(0.985 0 0)",
        card: "oklch(0.205 0 0)",
        "card-foreground": "oklch(0.985 0 0)",
        popover: "oklch(0.269 0 0)",
        "popover-foreground": "oklch(0.985 0 0)",
        primary: "var(--color-red-500)",
        "primary-foreground": "var(--color-red-50)",
        secondary: "oklch(0.269 0 0)",
        "secondary-foreground": "oklch(0.985 0 0)",
        muted: "oklch(0.269 0 0)",
        "muted-foreground": "oklch(0.708 0 0)",
        accent: "oklch(0.371 0 0)",
        "accent-foreground": "oklch(0.985 0 0)",
        destructive: "oklch(0.704 0.191 22.216)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(1 0 0 / 10%)",
        input: "oklch(1 0 0 / 15%)",
        ring: "var(--color-red-900)",
        "chart-1": "var(--color-red-400)",
        "chart-2": "var(--color-red-500)",
        "chart-3": "var(--color-red-600)",
        "chart-4": "var(--color-red-700)",
        "chart-5": "var(--color-red-800)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      }
    }
  },
  "rose": {
    label: "Rose",
    styles: {
      light: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        card: "oklch(1 0 0)",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "oklch(1 0 0)",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "var(--color-rose-600)",
        "primary-foreground": "var(--color-rose-50)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "var(--color-rose-400)",
        "chart-1": "var(--color-rose-500)",
        "chart-2": "var(--color-rose-600)",
        "chart-3": "var(--color-rose-700)",
        "chart-4": "var(--color-rose-800)",
        "chart-5": "var(--color-rose-900)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      },
      dark: {
        background: "oklch(0.145 0 0)",
        foreground: "oklch(0.985 0 0)",
        card: "oklch(0.205 0 0)",
        "card-foreground": "oklch(0.985 0 0)",
        popover: "oklch(0.269 0 0)",
        "popover-foreground": "oklch(0.985 0 0)",
        primary: "var(--color-rose-500)",
        "primary-foreground": "var(--color-rose-50)",
        secondary: "oklch(0.269 0 0)",
        "secondary-foreground": "oklch(0.985 0 0)",
        muted: "oklch(0.269 0 0)",
        "muted-foreground": "oklch(0.708 0 0)",
        accent: "oklch(0.371 0 0)",
        "accent-foreground": "oklch(0.985 0 0)",
        destructive: "oklch(0.704 0.191 22.216)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(1 0 0 / 10%)",
        input: "oklch(1 0 0 / 15%)",
        ring: "var(--color-rose-900)",
        "chart-1": "var(--color-rose-400)",
        "chart-2": "var(--color-rose-500)",
        "chart-3": "var(--color-rose-600)",
        "chart-4": "var(--color-rose-700)",
        "chart-5": "var(--color-rose-800)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      }
    }
  },
  "orange": {
    label: "Orange",
    styles: {
      light: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        card: "oklch(1 0 0)",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "oklch(1 0 0)",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "var(--color-orange-600)",
        "primary-foreground": "var(--color-orange-50)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "var(--color-orange-400)",
        "chart-1": "var(--color-orange-500)",
        "chart-2": "var(--color-orange-600)",
        "chart-3": "var(--color-orange-700)",
        "chart-4": "var(--color-orange-800)",
        "chart-5": "var(--color-orange-900)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      },
      dark: {
        background: "oklch(0.145 0 0)",
        foreground: "oklch(0.985 0 0)",
        card: "oklch(0.205 0 0)",
        "card-foreground": "oklch(0.985 0 0)",
        popover: "oklch(0.269 0 0)",
        "popover-foreground": "oklch(0.985 0 0)",
        primary: "var(--color-orange-500)",
        "primary-foreground": "var(--color-orange-50)",
        secondary: "oklch(0.269 0 0)",
        "secondary-foreground": "oklch(0.985 0 0)",
        muted: "oklch(0.269 0 0)",
        "muted-foreground": "oklch(0.708 0 0)",
        accent: "oklch(0.371 0 0)",
        "accent-foreground": "oklch(0.985 0 0)",
        destructive: "oklch(0.704 0.191 22.216)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(1 0 0 / 10%)",
        input: "oklch(1 0 0 / 15%)",
        ring: "var(--color-orange-900)",
        "chart-1": "var(--color-orange-400)",
        "chart-2": "var(--color-orange-500)",
        "chart-3": "var(--color-orange-600)",
        "chart-4": "var(--color-orange-700)",
        "chart-5": "var(--color-orange-800)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      }
    }
  },
  "yellow": {
    label: "Yellow",
    styles: {
      light: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        card: "oklch(1 0 0)",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "oklch(1 0 0)",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "var(--color-yellow-400)",
        "primary-foreground": "var(--color-yellow-900)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "var(--color-yellow-400)",
        "chart-1": "var(--color-yellow-500)",
        "chart-2": "var(--color-yellow-600)",
        "chart-3": "var(--color-yellow-700)",
        "chart-4": "var(--color-yellow-800)",
        "chart-5": "var(--color-yellow-900)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      },
      dark: {
        background: "oklch(0.145 0 0)",
        foreground: "oklch(0.985 0 0)",
        card: "oklch(0.205 0 0)",
        "card-foreground": "oklch(0.985 0 0)",
        popover: "oklch(0.269 0 0)",
        "popover-foreground": "oklch(0.985 0 0)",
        primary: "var(--color-yellow-500)",
        "primary-foreground": "var(--color-yellow-900)",
        secondary: "oklch(0.269 0 0)",
        "secondary-foreground": "oklch(0.985 0 0)",
        muted: "oklch(0.269 0 0)",
        "muted-foreground": "oklch(0.708 0 0)",
        accent: "oklch(0.371 0 0)",
        "accent-foreground": "oklch(0.985 0 0)",
        destructive: "oklch(0.704 0.191 22.216)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(1 0 0 / 10%)",
        input: "oklch(1 0 0 / 15%)",
        ring: "var(--color-yellow-900)",
        "chart-1": "var(--color-yellow-400)",
        "chart-2": "var(--color-yellow-500)",
        "chart-3": "var(--color-yellow-600)",
        "chart-4": "var(--color-yellow-700)",
        "chart-5": "var(--color-yellow-800)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      }
    }
  },
  "violet": {
    label: "Violet",
    styles: {
      light: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        card: "oklch(1 0 0)",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "oklch(1 0 0)",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "var(--color-violet-600)",
        "primary-foreground": "var(--color-violet-50)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "var(--color-violet-400)",
        "chart-1": "var(--color-violet-500)",
        "chart-2": "var(--color-violet-600)",
        "chart-3": "var(--color-violet-700)",
        "chart-4": "var(--color-violet-800)",
        "chart-5": "var(--color-violet-900)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      },
      dark: {
        background: "oklch(0.145 0 0)",
        foreground: "oklch(0.985 0 0)",
        card: "oklch(0.205 0 0)",
        "card-foreground": "oklch(0.985 0 0)",
        popover: "oklch(0.269 0 0)",
        "popover-foreground": "oklch(0.985 0 0)",
        primary: "var(--color-violet-500)",
        "primary-foreground": "var(--color-violet-50)",
        secondary: "oklch(0.269 0 0)",
        "secondary-foreground": "oklch(0.985 0 0)",
        muted: "oklch(0.269 0 0)",
        "muted-foreground": "oklch(0.708 0 0)",
        accent: "oklch(0.371 0 0)",
        "accent-foreground": "oklch(0.985 0 0)",
        destructive: "oklch(0.704 0.191 22.216)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(1 0 0 / 10%)",
        input: "oklch(1 0 0 / 15%)",
        ring: "var(--color-violet-900)",
        "chart-1": "var(--color-violet-400)",
        "chart-2": "var(--color-violet-500)",
        "chart-3": "var(--color-violet-600)",
        "chart-4": "var(--color-violet-700)",
        "chart-5": "var(--color-violet-800)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      }
    }
  },
  "amber": {
    label: "Amber",
    styles: {
      light: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        card: "oklch(1 0 0)",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "oklch(1 0 0)",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "var(--color-amber-600)",
        "primary-foreground": "var(--color-amber-50)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "var(--color-amber-400)",
        "chart-1": "var(--color-amber-500)",
        "chart-2": "var(--color-amber-600)",
        "chart-3": "var(--color-amber-700)",
        "chart-4": "var(--color-amber-800)",
        "chart-5": "var(--color-amber-900)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      },
      dark: {
        background: "oklch(0.145 0 0)",
        foreground: "oklch(0.985 0 0)",
        card: "oklch(0.205 0 0)",
        "card-foreground": "oklch(0.985 0 0)",
        popover: "oklch(0.269 0 0)",
        "popover-foreground": "oklch(0.985 0 0)",
        primary: "var(--color-amber-500)",
        "primary-foreground": "var(--color-amber-50)",
        secondary: "oklch(0.269 0 0)",
        "secondary-foreground": "oklch(0.985 0 0)",
        muted: "oklch(0.269 0 0)",
        "muted-foreground": "oklch(0.708 0 0)",
        accent: "oklch(0.371 0 0)",
        "accent-foreground": "oklch(0.985 0 0)",
        destructive: "oklch(0.704 0.191 22.216)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(1 0 0 / 10%)",
        input: "oklch(1 0 0 / 15%)",
        ring: "var(--color-amber-900)",
        "chart-1": "var(--color-amber-400)",
        "chart-2": "var(--color-amber-500)",
        "chart-3": "var(--color-amber-600)",
        "chart-4": "var(--color-amber-700)",
        "chart-5": "var(--color-amber-800)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      }
    }
  },
  "purple": {
    label: "Purple",
    styles: {
      light: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        card: "oklch(1 0 0)",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "oklch(1 0 0)",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "var(--color-purple-600)",
        "primary-foreground": "var(--color-purple-50)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "var(--color-purple-400)",
        "chart-1": "var(--color-purple-500)",
        "chart-2": "var(--color-purple-600)",
        "chart-3": "var(--color-purple-700)",
        "chart-4": "var(--color-purple-800)",
        "chart-5": "var(--color-purple-900)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      },
      dark: {
        background: "oklch(0.145 0 0)",
        foreground: "oklch(0.985 0 0)",
        card: "oklch(0.205 0 0)",
        "card-foreground": "oklch(0.985 0 0)",
        popover: "oklch(0.269 0 0)",
        "popover-foreground": "oklch(0.985 0 0)",
        primary: "var(--color-purple-500)",
        "primary-foreground": "var(--color-purple-50)",
        secondary: "oklch(0.269 0 0)",
        "secondary-foreground": "oklch(0.985 0 0)",
        muted: "oklch(0.269 0 0)",
        "muted-foreground": "oklch(0.708 0 0)",
        accent: "oklch(0.371 0 0)",
        "accent-foreground": "oklch(0.985 0 0)",
        destructive: "oklch(0.704 0.191 22.216)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(1 0 0 / 10%)",
        input: "oklch(1 0 0 / 15%)",
        ring: "var(--color-purple-900)",
        "chart-1": "var(--color-purple-400)",
        "chart-2": "var(--color-purple-500)",
        "chart-3": "var(--color-purple-600)",
        "chart-4": "var(--color-purple-700)",
        "chart-5": "var(--color-purple-800)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      }
    }
  },
  "teal": {
    label: "Teal",
    styles: {
      light: {
        background: "oklch(1 0 0)",
        foreground: "oklch(0.145 0 0)",
        card: "oklch(1 0 0)",
        "card-foreground": "oklch(0.145 0 0)",
        popover: "oklch(1 0 0)",
        "popover-foreground": "oklch(0.145 0 0)",
        primary: "var(--color-teal-600)",
        "primary-foreground": "var(--color-teal-50)",
        secondary: "oklch(0.97 0 0)",
        "secondary-foreground": "oklch(0.205 0 0)",
        muted: "oklch(0.97 0 0)",
        "muted-foreground": "oklch(0.556 0 0)",
        accent: "oklch(0.97 0 0)",
        "accent-foreground": "oklch(0.205 0 0)",
        destructive: "oklch(0.577 0.245 27.325)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(0.922 0 0)",
        input: "oklch(0.922 0 0)",
        ring: "var(--color-teal-400)",
        "chart-1": "var(--color-teal-500)",
        "chart-2": "var(--color-teal-600)",
        "chart-3": "var(--color-teal-700)",
        "chart-4": "var(--color-teal-800)",
        "chart-5": "var(--color-teal-900)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      },
      dark: {
        background: "oklch(0.145 0 0)",
        foreground: "oklch(0.985 0 0)",
        card: "oklch(0.205 0 0)",
        "card-foreground": "oklch(0.985 0 0)",
        popover: "oklch(0.269 0 0)",
        "popover-foreground": "oklch(0.985 0 0)",
        primary: "var(--color-teal-500)",
        "primary-foreground": "var(--color-teal-50)",
        secondary: "oklch(0.269 0 0)",
        "secondary-foreground": "oklch(0.985 0 0)",
        muted: "oklch(0.269 0 0)",
        "muted-foreground": "oklch(0.708 0 0)",
        accent: "oklch(0.371 0 0)",
        "accent-foreground": "oklch(0.985 0 0)",
        destructive: "oklch(0.704 0.191 22.216)",
        "destructive-foreground": "oklch(0.98 0 0)",
        border: "oklch(1 0 0 / 10%)",
        input: "oklch(1 0 0 / 15%)",
        ring: "var(--color-teal-900)",
        "chart-1": "var(--color-teal-400)",
        "chart-2": "var(--color-teal-500)",
        "chart-3": "var(--color-teal-600)",
        "chart-4": "var(--color-teal-700)",
        "chart-5": "var(--color-teal-800)",
        radius: "0.625rem",
        "font-sans": "ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
        "font-mono": "ui-monospace, SFMono-Regular, 'SF Mono', Consolas, 'Liberation Mono', Menlo, monospace",
      }
    }
  }
};